{
  "comments": [
    "Cannot launch remote manual test suites through VPN connection.\n\nDespite disabling the firewalls on both sides, launching a remote manual test \nsuites through VPN connection causing the local workbench to generate the error \ncited in https://bugs.eclipse.org/bugs/show_bug.cgi?id\u003d112780.",
    "P2 Highly desirable and planned for this release, but not stop ship \nnormal A problem making a function difficult to use but no special work around \nis required\n",
    "This is only a problem when specifying the host name.  Using the IP address of \nthe host in the location artifact works.",
    "This defect seems to be specific to the reporter\u0027s specific machine since other \nTPTP committers are able to launch manual tests on the target machine with both \nthe host name and IP address.  Returning as \u0027works for me\u0027 until we see this \nsymptom again.",
    "Closing.",
    "This defect is reoccurring, albeit sporadically, with both manual and JUnit \ntest suites.  Interestingly, the problem seems to be seen more when connecting \nfrom home over my wireless network.  Here are the exceptions from running the \nenclosed test suites using the TPTP_v4_1_0_200510311029 driver:\n\n!ENTRY org.eclipse.hyades.test.core 1 0 2005-11-01 08:00:36.509\n!MESSAGE org.eclipse.hyades.execution.core.DaemonConnectException\n!STACK 0\norg.eclipse.hyades.execution.core.DaemonConnectException\n\tat org.eclipse.hyades.execution.local.NodeImpl._connect\n(NodeImpl.java:225)\n\tat org.eclipse.hyades.execution.local.NodeImpl.connect\n(NodeImpl.java:360)\n\tat org.eclipse.hyades.execution.local.NodeImpl.connect\n(NodeImpl.java:347)\n\tat org.eclipse.hyades.execution.harness.TestExecutionHarness$4.run\n(TestExecutionHarness.java:2303)\n\tat java.lang.Thread.run(Thread.java:568)\nCaused by: \norg.eclipse.hyades.internal.execution.local.control.InactiveProcessException\n\tat \norg.eclipse.hyades.internal.execution.local.control.ProcessImpl.getProcessId\n(ProcessImpl.java:483)\n\tat org.eclipse.hyades.execution.local.NodeImpl._connect\n(NodeImpl.java:220)\n\t... 4 more\n\n!ENTRY org.eclipse.hyades.test.core 4 0 2005-11-01 08:00:51.711\n!MESSAGE IWAT4039E The Test Execution Harness reported the following \nproblems:org.eclipse.core.runtime.CoreException\n!STACK 1\norg.eclipse.core.runtime.CoreException: IWAT4039E The Test Execution Harness \nreported the following problems:Connection refused on host \npaules.torolab.ibm.com.\n\tat \norg.eclipse.hyades.test.core.launch.delegates.AbstractLaunchConfigurationDelegat\ne2.launch(AbstractLaunchConfigurationDelegate2.java:178)\n\tat org.eclipse.debug.internal.core.LaunchConfiguration.launch\n(LaunchConfiguration.java:590)\n\tat org.eclipse.debug.internal.core.LaunchConfiguration.launch\n(LaunchConfiguration.java:515)\n\tat org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch\n(DebugUIPlugin.java:733)\n\tat org.eclipse.debug.internal.ui.DebugUIPlugin$6.run\n(DebugUIPlugin.java:931)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:76)\n!SUBENTRY 1 org.eclipse.hyades.test.core 4 0 2005-11-01 08:00:51.711\n!MESSAGE IWAT4039E The Test Execution Harness reported the following \nproblems:Connection refused on host paules.torolab.ibm.com.\n\n!ENTRY org.eclipse.hyades.test.core 1 0 2005-11-01 08:02:44.904\n!MESSAGE org.eclipse.hyades.execution.core.DaemonConnectException\n!STACK 0\norg.eclipse.hyades.execution.core.DaemonConnectException\n\tat org.eclipse.hyades.execution.local.NodeImpl._connect\n(NodeImpl.java:225)\n\tat org.eclipse.hyades.execution.local.NodeImpl.connect\n(NodeImpl.java:360)\n\tat org.eclipse.hyades.execution.local.NodeImpl.connect\n(NodeImpl.java:347)\n\tat org.eclipse.hyades.execution.harness.TestExecutionHarness$4.run\n(TestExecutionHarness.java:2303)\n\tat java.lang.Thread.run(Thread.java:568)\nCaused by: \norg.eclipse.hyades.internal.execution.local.control.InactiveProcessException\n\tat \norg.eclipse.hyades.internal.execution.local.control.ProcessImpl.getProcessId\n(ProcessImpl.java:483)\n\tat org.eclipse.hyades.execution.local.NodeImpl._connect\n(NodeImpl.java:220)\n\t... 4 more\n\n!ENTRY org.eclipse.hyades.test.core 4 0 2005-11-01 08:02:59.945\n!MESSAGE IWAT4039E The Test Execution Harness reported the following \nproblems:org.eclipse.core.runtime.CoreException\n!STACK 1\norg.eclipse.core.runtime.CoreException: IWAT4039E The Test Execution Harness \nreported the following problems:Connection refused on host \npaules.torolab.ibm.com.\n\tat \norg.eclipse.hyades.test.core.launch.delegates.AbstractLaunchConfigurationDelegat\ne2.launch(AbstractLaunchConfigurationDelegate2.java:178)\n\tat org.eclipse.debug.internal.core.LaunchConfiguration.launch\n(LaunchConfiguration.java:590)\n\tat org.eclipse.debug.internal.core.LaunchConfiguration.launch\n(LaunchConfiguration.java:515)\n\tat org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch\n(DebugUIPlugin.java:733)\n\tat org.eclipse.debug.internal.ui.DebugUIPlugin$6.run\n(DebugUIPlugin.java:931)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:76)\n!SUBENTRY 1 org.eclipse.hyades.test.core 4 0 2005-11-01 08:02:59.945\n!MESSAGE IWAT4039E The Test Execution Harness reported the following \nproblems:Connection refused on host paules.torolab.ibm.com.\n",
    "Created an attachment (id\u003d29051)\nTest project.\n",
    "This defect seems to be specific to the reporter\u0027s specific machine since \neverything works as designed when launching manual and JUnit test suites \nbetween Windows XP --\u003e Windows XP and Windows XP --\u003e Linux using both \nthe host name and IP address.  Returning as \u0027works for me\u0027 until we see this \nsymptom again.\n",
    "This problem appears to have disappeared using the TPTP_v4_1_0_200511070100 \nbuild, host name of the host in the location artifact and disabling the \nfirewall on both the client and server.  "
  ],
  "commentCreationDates": [
    "2005-10-17T15:44:42+02:00",
    "2005-10-17T15:46:05+02:00",
    "2005-10-20T21:58:57+02:00",
    "2005-10-20T22:28:03+02:00",
    "2005-10-23T17:33:05+02:00",
    "2005-11-01T13:22:15+01:00",
    "2005-11-01T13:22:48+01:00",
    "2005-11-01T19:00:32+01:00",
    "2005-11-07T14:34:58+01:00"
  ],
  "traces": [
    {
      "exceptionType": "org.eclipse.hyades.execution.core.DaemonConnectException",
      "elements": [
        {
          "method": "org.eclipse.hyades.execution.local.NodeImpl._connect",
          "source": "NodeImpl.java:225"
        },
        {
          "method": "org.eclipse.hyades.execution.local.NodeImpl.connect",
          "source": "NodeImpl.java:360"
        },
        {
          "method": "org.eclipse.hyades.execution.local.NodeImpl.connect",
          "source": "NodeImpl.java:347"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.TestExecutionHarness$4.run",
          "source": "TestExecutionHarness.java:2303"
        },
        {
          "method": "java.lang.Thread.run",
          "source": "Thread.java:568"
        }
      ],
      "causedBy": {
        "exceptionType": "org.eclipse.hyades.internal.execution.local.control.InactiveProcessException",
        "elements": [
          {
            "method": "org.eclipse.hyades.internal.execution.local.control.ProcessImpl.getProcessId",
            "source": "ProcessImpl.java:483"
          },
          {
            "method": "org.eclipse.hyades.execution.local.NodeImpl._connect",
            "source": "NodeImpl.java:220"
          }
        ],
        "number": 0,
        "commentIndex": 0
      },
      "number": 0,
      "commentIndex": 5,
      "bugId": "112784",
      "date": "2005-11-01T13:22:15+01:00",
      "product": "TPTP Testing",
      "component": "Test.Execution.ExecutionHarness",
      "severity": "normal"
    },
    {
      "exceptionType": "org.eclipse.core.runtime.CoreException",
      "message": "IWAT4039E The Test Execution Harness  reported the following problems:Connection refused on host  paules.torolab.ibm.com.",
      "elements": [
        {
          "method": "org.eclipse.hyades.test.core.launch.delegates.AbstractLaunchConfigurationDelegate2.launch",
          "source": "AbstractLaunchConfigurationDelegate2.java:178"
        },
        {
          "method": "org.eclipse.debug.internal.core.LaunchConfiguration.launch",
          "source": "LaunchConfiguration.java:590"
        },
        {
          "method": "org.eclipse.debug.internal.core.LaunchConfiguration.launch",
          "source": "LaunchConfiguration.java:515"
        },
        {
          "method": "org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch",
          "source": "DebugUIPlugin.java:733"
        },
        {
          "method": "org.eclipse.debug.internal.ui.DebugUIPlugin$6.run",
          "source": "DebugUIPlugin.java:931"
        },
        {
          "method": "org.eclipse.core.internal.jobs.Worker.run",
          "source": "Worker.java:76"
        }
      ],
      "number": 1,
      "commentIndex": 5,
      "bugId": "112784",
      "date": "2005-11-01T13:22:15+01:00",
      "product": "TPTP Testing",
      "component": "Test.Execution.ExecutionHarness",
      "severity": "normal"
    },
    {
      "exceptionType": "org.eclipse.hyades.execution.core.DaemonConnectException",
      "elements": [
        {
          "method": "org.eclipse.hyades.execution.local.NodeImpl._connect",
          "source": "NodeImpl.java:225"
        },
        {
          "method": "org.eclipse.hyades.execution.local.NodeImpl.connect",
          "source": "NodeImpl.java:360"
        },
        {
          "method": "org.eclipse.hyades.execution.local.NodeImpl.connect",
          "source": "NodeImpl.java:347"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.TestExecutionHarness$4.run",
          "source": "TestExecutionHarness.java:2303"
        },
        {
          "method": "java.lang.Thread.run",
          "source": "Thread.java:568"
        }
      ],
      "causedBy": {
        "exceptionType": "org.eclipse.hyades.internal.execution.local.control.InactiveProcessException",
        "elements": [
          {
            "method": "org.eclipse.hyades.internal.execution.local.control.ProcessImpl.getProcessId",
            "source": "ProcessImpl.java:483"
          },
          {
            "method": "org.eclipse.hyades.execution.local.NodeImpl._connect",
            "source": "NodeImpl.java:220"
          }
        ],
        "number": 0,
        "commentIndex": 0
      },
      "number": 2,
      "commentIndex": 5,
      "bugId": "112784",
      "date": "2005-11-01T13:22:15+01:00",
      "product": "TPTP Testing",
      "component": "Test.Execution.ExecutionHarness",
      "severity": "normal"
    },
    {
      "exceptionType": "org.eclipse.core.runtime.CoreException",
      "message": "IWAT4039E The Test Execution Harness  reported the following problems:Connection refused on host  paules.torolab.ibm.com.",
      "elements": [
        {
          "method": "org.eclipse.hyades.test.core.launch.delegates.AbstractLaunchConfigurationDelegate2.launch",
          "source": "AbstractLaunchConfigurationDelegate2.java:178"
        },
        {
          "method": "org.eclipse.debug.internal.core.LaunchConfiguration.launch",
          "source": "LaunchConfiguration.java:590"
        },
        {
          "method": "org.eclipse.debug.internal.core.LaunchConfiguration.launch",
          "source": "LaunchConfiguration.java:515"
        },
        {
          "method": "org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch",
          "source": "DebugUIPlugin.java:733"
        },
        {
          "method": "org.eclipse.debug.internal.ui.DebugUIPlugin$6.run",
          "source": "DebugUIPlugin.java:931"
        },
        {
          "method": "org.eclipse.core.internal.jobs.Worker.run",
          "source": "Worker.java:76"
        }
      ],
      "number": 3,
      "commentIndex": 5,
      "bugId": "112784",
      "date": "2005-11-01T13:22:15+01:00",
      "product": "TPTP Testing",
      "component": "Test.Execution.ExecutionHarness",
      "severity": "normal"
    }
  ],
  "groupId": "112784",
  "bugId": "112784",
  "date": "2005-10-17T15:44:42+02:00",
  "product": "TPTP Testing",
  "component": "Test.Execution.ExecutionHarness",
  "severity": "normal"
}