{
  "comments": [
    "1. ReflectionBasedReferenceTypeDelegateTest.testCompareSubclassDelegates() \n\njunit.framework.AssertionFailedError: Errors:Couldn\u0027t find void java.util.HashMap.onEntry() in the bcel set \nCouldn\u0027t find void java.util.HashMap.onExit() in the bcel set \nCouldn\u0027t find void java.util.HashMap.transfer0(java.util.HashMap$Entry[]) in the bcel set \n\n? ? ? ? at junit.framework.Assert.fail(Assert.java:47) \n? ? ? ? at junit.framework.Assert.assertTrue(Assert.java:20) \n? ? ? ? at org.aspectj.weaver.reflect.ReflectionBasedReferenceTypeDelegateTest.testCompareSubclassDelegates(ReflectionBasedReferenceTypeDelegateTest.java:278) \n? ? ? ? at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) \n? ? ? ? at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) \n? ? ? ? at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) \n? ? ? ? at java.lang.reflect.Method.invoke(Method.java:615) \n? ? ? ? at junit.framework.TestCase.runTest(TestCase.java:154) \n? ? ? ? at junit.framework.TestCase.runBare(TestCase.java:127) \n? ? ? ? at junit.framework.TestResult$1.protect(TestResult.java:106) \n? ? ? ? at junit.framework.TestResult.runProtected(TestResult.java:124) \n? ? ? ? at junit.framework.TestResult.run(TestResult.java:109) \n? ? ? ? at junit.framework.TestCase.run(TestCase.java:118) \n? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) \n? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) \n? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) \n? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) \n? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) \n? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) \n? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) \n? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) \n? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:478) \n? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:344) \n? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196) \n\nThis failure occures because when we compare BeclWorld with ReflectionWorld we are still picking up the default (Sun) version of HashMap in JRE15_LIB for BCEL. The solution is to create both worlds with the same class loader.\n\n2. Ajc150Tests.testModifierOverrides() \n\njunit.framework.AssertionFailedError: Expecting output: \nexecution(void pr119749.C.m()): execMe[@pr119749$Me()] \nexecution(void pr119749.C.m()): execEx \nBut found output: \nexecution(void pr119749.C.m()): execMe[@pr119749.Me()] \nexecution(void pr119749.C.m()): execEx \n\nFirst difference is on line 1 \n\n? ? ? ? at junit.framework.Assert.fail(Assert.java:47) \n? ? ? ? at org.aspectj.testing.OutputSpec.matchAgainst(OutputSpec.java:58) \n? ? ? ? at org.aspectj.testing.RunSpec.execute(RunSpec.java:61) \n? ? ? ? at org.aspectj.testing.AjcTest.runTest(AjcTest.java:68) \n? ? ? ? at org.aspectj.testing.XMLBasedAjcTestCase.runTest(XMLBasedAjcTestCase.java:111) \n? ? ? ? at org.aspectj.systemtest.ajc150.Ajc150Tests.testModifierOverrides(Ajc150Tests.java:852) \n? ? ? ? at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) \n? ? ? ? at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) \n? ? ? ? at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) \n? ? ? ? at java.lang.reflect.Method.invoke(Method.java:615) \n? ? ? ? at junit.framework.TestCase.runTest(TestCase.java:154) \n? ? ? ? at junit.framework.TestCase.runBare(TestCase.java:127) \n? ? ? ? at junit.framework.TestResult$1.protect(TestResult.java:106) \n? ? ? ? at junit.framework.TestResult.runProtected(TestResult.java:124) \n? ? ? ? at junit.framework.TestResult.run(TestResult.java:109) \n? ? ? ? at junit.framework.TestCase.run(TestCase.java:118) \n? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) \n? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) \n? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) \n? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) \n? ? ? ? at junit.extensions.TestDecorator.basicRun(TestDecorator.java:22) \n? ? ? ? at junit.extensions.TestSetup$1.protect(TestSetup.java:19) \n? ? ? ? at junit.framework.TestResult.runProtected(TestResult.java:124) \n? ? ? ? at junit.extensions.TestSetup.run(TestSetup.java:23) \n? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) \n? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) \n? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) \n? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) \n? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) \n? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) \n? ? ? ? at junit.framework.TestSuite.runTest(TestSuite.java:208) \n? ? ? ? at junit.framework.TestSuite.run(TestSuite.java:203) \n? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:478) \n? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:344) \n? ? ? ? at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196) \n\nThis failure is due a difference between JDKs in the implementation of toString() for annotations.",
    "Created an attachment (id\u003d31760)\nFixes to 2 harness tests\n\n",
    "Created an attachment (id\u003d31804)\nFixes to harness tests\n\nAlso remove public constructors that use Class.getClassLoader().",
    "fix now available"
  ],
  "commentCreationDates": [
    "2005-12-14T16:58:04+01:00",
    "2005-12-14T17:20:23+01:00",
    "2005-12-15T11:38:36+01:00",
    "2005-12-19T07:09:10+01:00"
  ],
  "traces": [
    {
      "exceptionType": "junit.framework.AssertionFailedError",
      "message": "Errors:Couldn\u0027t find void java.util.HashMap.onEntry() in the bcel set  Couldn\u0027t find void java.util.HashMap.onExit() in the bcel set  Couldn\u0027t find void java.util.HashMap.transfer0(java.util.HashMap$Entry[]) in the bcel set   ? ? ? ?",
      "elements": [
        {
          "method": "junit.framework.Assert.fail",
          "source": "Assert.java:47"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "120909",
      "date": "2005-12-14T16:58:04+01:00",
      "product": "AspectJ",
      "component": "Compiler",
      "severity": "normal"
    },
    {
      "exceptionType": "junit.framework.AssertionFailedError",
      "message": "Expecting output:  execution(void pr119749.C.m()): execMe[@pr119749$Me()]  execution(void pr119749.C.m()): execEx  But found output:  execution(void pr119749.C.m()): execMe[@pr119749.Me()]  execution(void pr119749.C.m()): execEx   First difference is on line 1   ? ? ? ?",
      "elements": [
        {
          "method": "junit.framework.Assert.fail",
          "source": "Assert.java:47"
        }
      ],
      "number": 1,
      "commentIndex": 0,
      "bugId": "120909",
      "date": "2005-12-14T16:58:04+01:00",
      "product": "AspectJ",
      "component": "Compiler",
      "severity": "normal"
    }
  ],
  "groupId": "120909",
  "bugId": "120909",
  "date": "2005-12-14T16:58:04+01:00",
  "product": "AspectJ",
  "component": "Compiler",
  "severity": "normal"
}