{
  "comments": [
    "build I20060428-1315\n\npublic class X {\n    void foo(Object o) {\n    \tfoo(#);\n    }\n}\n\n1) select \u0027foo\u0027 in \u0027foo(#)\u0027\n2) do F3\nCode Select fail\n\nAnother test case:\npublic class X {\n    void foo(Object o) {\n    \tfoo(new Object(){#});\n    }\n}\n1) select \u0027foo\u0027 in \u0027foo(#)\u0027\n2) do F3\nCode Select fail. This failure is due to an internal ArraiIndexOuOfBoundException.\n\nException caught by SelectionEngine:\njava.lang.ArrayIndexOutOfBoundsException: -1\n\tat org.eclipse.jdt.internal.codeassist.impl.AssistParser.getTypeReference(AssistParser.java:814)\n\tat org.eclipse.jdt.internal.codeassist.select.SelectionParser.checkRecoveredType(SelectionParser.java:143)\n\tat org.eclipse.jdt.internal.codeassist.select.SelectionParser.selectionIdentifierCheck(SelectionParser.java:1201)\n\tat org.eclipse.jdt.internal.codeassist.select.SelectionParser.updateRecoveryState(SelectionParser.java:1215)\n\tat org.eclipse.jdt.internal.compiler.parser.Parser.resumeOnSyntaxError(Parser.java:9915)\n\tat org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:8784)",
    "This is not a regression, the exception is internally caught and the second test case would fail even without the exception.\n\nDeferred post 3.2."
  ],
  "commentCreationDates": [
    "2006-05-03T12:01:32+02:00",
    "2006-05-03T12:05:51+02:00"
  ],
  "traces": [
    {
      "exceptionType": "java.lang.ArrayIndexOutOfBoundsException",
      "message": "-1",
      "elements": [
        {
          "method": "org.eclipse.jdt.internal.codeassist.impl.AssistParser.getTypeReference",
          "source": "AssistParser.java:814"
        },
        {
          "method": "org.eclipse.jdt.internal.codeassist.select.SelectionParser.checkRecoveredType",
          "source": "SelectionParser.java:143"
        },
        {
          "method": "org.eclipse.jdt.internal.codeassist.select.SelectionParser.selectionIdentifierCheck",
          "source": "SelectionParser.java:1201"
        },
        {
          "method": "org.eclipse.jdt.internal.codeassist.select.SelectionParser.updateRecoveryState",
          "source": "SelectionParser.java:1215"
        },
        {
          "method": "org.eclipse.jdt.internal.compiler.parser.Parser.resumeOnSyntaxError",
          "source": "Parser.java:9915"
        },
        {
          "method": "org.eclipse.jdt.internal.compiler.parser.Parser.parse",
          "source": "Parser.java:8784"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "139907",
      "date": "2006-05-03T12:01:32+02:00",
      "product": "JDT",
      "component": "Core",
      "severity": "normal"
    }
  ],
  "groupId": "139907",
  "bugId": "139907",
  "date": "2006-05-03T12:01:32+02:00",
  "product": "JDT",
  "component": "Core",
  "severity": "normal"
}