{
  "comments": [
    "I have a project with a version 3.6 junit.jar on the classpath. In 3.0M8 when I\nrun a test with an assertEquals() that fails, I get this error:\n\njava.lang.NoClassDefFoundError: junit/framework/ComparisonFailure\n\tat\norg.eclipse.jdt.internal.junit.runner.RemoteTestRunner.addFailure(RemoteTestRunner.java:533)\n\tat junit.framework.TestResult.addFailure(TestResult.java:46)\n\tat junit.framework.TestResult.runProtected(TestResult.java:127)\n\tat junit.framework.TestResult.run(TestResult.java:109)\n\tat junit.framework.TestCase.run(TestCase.java:131)\n\tat junit.framework.TestSuite.runTest(TestSuite.java:173)\n\tat junit.framework.TestSuite.run(TestSuite.java:168)\n\tat\norg.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:410)\n\tat\norg.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:294)\n\tat\norg.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:182)\nException in thread \"main\" \n\nThis used to work with Eclipse 2.1 (which also had JUnit 3.8.1 built in), and it\ndisappears when I upgrade my copy of junit.jar to 3.8.1 to match the Eclipse one.",
    "fixed - removed static dependency on ComparisonFailure"
  ],
  "commentCreationDates": [
    "2004-05-17T18:34:32+02:00",
    "2004-05-18T11:12:03+02:00"
  ],
  "traces": [
    {
      "exceptionType": "java.lang.NoClassDefFoundError",
      "message": "junit/framework/ComparisonFailure",
      "elements": [
        {
          "method": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.addFailure",
          "source": "RemoteTestRunner.java:533"
        },
        {
          "method": "junit.framework.TestResult.addFailure",
          "source": "TestResult.java:46"
        },
        {
          "method": "junit.framework.TestResult.runProtected",
          "source": "TestResult.java:127"
        },
        {
          "method": "junit.framework.TestResult.run",
          "source": "TestResult.java:109"
        },
        {
          "method": "junit.framework.TestCase.run",
          "source": "TestCase.java:131"
        },
        {
          "method": "junit.framework.TestSuite.runTest",
          "source": "TestSuite.java:173"
        },
        {
          "method": "junit.framework.TestSuite.run",
          "source": "TestSuite.java:168"
        },
        {
          "method": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests",
          "source": "RemoteTestRunner.java:410"
        },
        {
          "method": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run",
          "source": "RemoteTestRunner.java:294"
        },
        {
          "method": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main",
          "source": "RemoteTestRunner.java:182"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "62503",
      "date": "2004-05-17T18:34:32+02:00",
      "product": "JDT",
      "component": "UI",
      "severity": "normal"
    }
  ],
  "groupId": "62503",
  "bugId": "62503",
  "date": "2004-05-17T18:34:32+02:00",
  "product": "JDT",
  "component": "UI",
  "severity": "normal"
}