{
  "comments": [
    "I200405202114\nI had pressed the synchronize button and was prompted for my password (first \nattempt to synch with this build).\nI hit cancel. \nIt prompted me again; I hit cancel\nThen I realized I needed to cancel the synchronize progress monitor.\nSo I hit this cancel.\nNow I do not seem to be able to log in to synchronize...ack!\n\nSeveral of these were in the DOS console\norg.eclipse.core.runtime.OperationCanceledException: Operation cancelled \nbecause\n login cancelled\n        at \norg.eclipse.team.internal.ccvs.ui.WorkbenchUserAuthenticator.promptFo\nrUserInfo(WorkbenchUserAuthenticator.java:76)\n        at \norg.eclipse.team.internal.ccvs.ssh2.JSchSession$MyUserInfo.promptSecr\net(JSchSession.java:143)\n        at \norg.eclipse.team.internal.ccvs.ssh2.JSchSession$MyUserInfo.promptPass\nword(JSchSession.java:160)\n        at com.jcraft.jsch.UserAuthPassword.start(Unknown Source)\n        at com.jcraft.jsch.Session.connect(Unknown Source)\n        at org.eclipse.team.internal.ccvs.ssh2.JSchSession.getSession\n(JSchSessio\nn.java:281)\n        at \norg.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.internalO\npen(CVSSSH2ServerConnection.java:119)\n        at org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.access$0\n(\nCVSSSH2ServerConnection.java:108)\n        at org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection$3.run\n(CVS\nSSH2ServerConnection.java:179)\n        at java.lang.Thread.run(Thread.java:534)\norg.eclipse.core.runtime.OperationCanceledException: Operation cancelled \nbecause\n login cancelled\n        at \norg.eclipse.team.internal.ccvs.ui.WorkbenchUserAuthenticator.promptFo\nrUserInfo(WorkbenchUserAuthenticator.java:76)\n        at \norg.eclipse.team.internal.ccvs.ssh2.JSchSession$MyUserInfo.promptSecr\net(JSchSession.java:143)\n        at \norg.eclipse.team.internal.ccvs.ssh2.JSchSession$MyUserInfo.promptPass\nword(JSchSession.java:160)\n        at com.jcraft.jsch.UserAuthPassword.start(Unknown Source)\n        at com.jcraft.jsch.Session.connect(Unknown Source)\n        at org.eclipse.team.internal.ccvs.ssh2.JSchSession.getSession\n(JSchSessio\nn.java:281)\n        at \norg.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.internalO\npen(CVSSSH2ServerConnection.java:119)\n        at org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.access$0\n(\nCVSSSH2ServerConnection.java:108)\n        at org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection$3.run\n(CVS\nSSH2ServerConnection.java:179)\n        at java.lang.Thread.run(Thread.java:534)",
    "I don\u0027t know if it\u0027s related but the following happend to me when tryiung to \ncommit:\n\n1) Got prompted for password for extssh connection and entered the password\n2) Maybe it was a good password and maybe it wasn\u0027t but I got prompted again.\n3) Entered the password again and got an authentication error dialog\n4) Tried to commit again and it worked.\n\nThe password I entered in step 3 must have been right so I shouldn\u0027t have \ngotten the error.",
    "Is it reprodusible easily?\nI tried, but I could not.\nHow about the checkbox for \u0027save password\u0027?",
    "so I can\u0027t dupe the error to the DOS console. I tried a bunch of different\nscenarios. However, I was able to get the following printed to the console after\nI tried to authenticate too many times with the wrong password.\n\nSSH_MSG_DISCONNECT: 2 too many failed userauth_requests \n\nymnk, could you do a quick review of your code to see if you are printing stuff\nto stdout? If possible you could add these to the exceptions instead.",
    "Comment for #3\nI have updated jsch-0.1.16.jar on CVS repository and\nit will not print \u0027SSH_MSG_DISCONNECT...\u0027 to stderr.",
    "\n\n*** This bug has been marked as a duplicate of 63002 ***"
  ],
  "commentCreationDates": [
    "2004-05-21T18:18:08+02:00",
    "2004-05-27T20:11:16+02:00",
    "2004-05-28T02:47:41+02:00",
    "2004-05-28T18:25:09+02:00",
    "2004-05-29T11:53:31+02:00",
    "2004-06-04T20:49:21+02:00"
  ],
  "traces": [
    {
      "exceptionType": "org.eclipse.core.runtime.OperationCanceledException",
      "message": "Operation cancelled  because  login cancelled",
      "elements": [
        {
          "method": "org.eclipse.team.internal.ccvs.ui.WorkbenchUserAuthenticator.promptForUserInfo",
          "source": "WorkbenchUserAuthenticator.java:76"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.JSchSession$MyUserInfo.promptSecret",
          "source": "JSchSession.java:143"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.JSchSession$MyUserInfo.promptPassword",
          "source": "JSchSession.java:160"
        },
        {
          "method": "com.jcraft.jsch.UserAuthPassword.start",
          "source": "Unknown Source"
        },
        {
          "method": "com.jcraft.jsch.Session.connect",
          "source": "Unknown Source"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.JSchSession.getSession",
          "source": "JSchSessio n.java:281"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.internalOpen",
          "source": "CVSSSH2ServerConnection.java:119"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.access$0",
          "source": " CVSSSH2ServerConnection.java:108"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection$3.run",
          "source": "CVS SSH2ServerConnection.java:179"
        },
        {
          "method": "java.lang.Thread.run",
          "source": "Thread.java:534"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "63442",
      "duplicateId": "63002",
      "date": "2004-05-21T18:18:08+02:00",
      "product": "Platform",
      "component": "Team",
      "severity": "normal"
    },
    {
      "exceptionType": "org.eclipse.core.runtime.OperationCanceledException",
      "message": "Operation cancelled  because  login cancelled",
      "elements": [
        {
          "method": "org.eclipse.team.internal.ccvs.ui.WorkbenchUserAuthenticator.promptForUserInfo",
          "source": "WorkbenchUserAuthenticator.java:76"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.JSchSession$MyUserInfo.promptSecret",
          "source": "JSchSession.java:143"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.JSchSession$MyUserInfo.promptPassword",
          "source": "JSchSession.java:160"
        },
        {
          "method": "com.jcraft.jsch.UserAuthPassword.start",
          "source": "Unknown Source"
        },
        {
          "method": "com.jcraft.jsch.Session.connect",
          "source": "Unknown Source"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.JSchSession.getSession",
          "source": "JSchSessio n.java:281"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.internalOpen",
          "source": "CVSSSH2ServerConnection.java:119"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.access$0",
          "source": " CVSSSH2ServerConnection.java:108"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection$3.run",
          "source": "CVS SSH2ServerConnection.java:179"
        },
        {
          "method": "java.lang.Thread.run",
          "source": "Thread.java:534"
        }
      ],
      "number": 1,
      "commentIndex": 0,
      "bugId": "63442",
      "duplicateId": "63002",
      "date": "2004-05-21T18:18:08+02:00",
      "product": "Platform",
      "component": "Team",
      "severity": "normal"
    }
  ],
  "groupId": "63002",
  "bugId": "63442",
  "duplicateId": "63002",
  "date": "2004-05-21T18:18:08+02:00",
  "product": "Platform",
  "component": "Team",
  "severity": "normal"
}