{
  "comments": [
    "Set up a failing JUnit test.\nRun it.\nDouble click the failed test in \"Failures\" pane in the JUnit view.\n\nCurrent behaviour:\nAn editor is opened.  The cursor is on the first line of the failing JUnit test\nmethod.\n\nExpected behaviour:\nAn editor should be opened.  The cursor should be on the line of the JUnit\nassertion that failed.",
    "Which build are you using? Is there anything in the log file?",
    "I\u0027m using 3.0 GA, build 200406251208.  No there isn\u0027t anything in the log file.\n\nAs an example, the relevant lines in the test failure backtrace says:\n\njunit.framework.AssertionFailedError: Logs should have shrunk when becoming \u003e\nmaxTotalLogSize bytes\n\tat junit/framework/Assert.fail(Ljava/lang/String;)V(Assert.java:47)\n\tat junit/framework/Assert.assertTrue(Ljava/lang/String;Z)V(Assert.java:20)\n\tat\ncom/jrockit/console/persistence/test/PairStorageTest.testSetMaxTotalLogSize()V(PairStorageTest.java:1042)\n\tat\njrockit/reflect/NativeMethodInvoker.invoke0(Ljava/lang/Object;ILjava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;(Unknown\nSource)\n...\n\nIf I double click the failed test case I\u0027m taken to the top of\ntestSetMaxTotalLogSize() at line 996 of PairStorageTest.java, rather than to\nline 1042 of the same file where the assertion actually failed according to the\nabove backtrace.\n\nIt seems as if Eclipse only reads the failed method name from the backtrace\nrather than reading the line number of the failure.\n",
    "Time permitted.",
    "Moving back to the JDT/UI inbox",
    "Agree that this would be helpful: It should be possible to look through the stacktrace of you find the signature of the test method and use that line.",
    "Yep, the assertion failure could occur in another method than the failing test method (even in another class).\n\nimport junit.framework.TestCase;\npublic class Failing extends TestCase {\n\tpublic void testFail() throws Exception {\n\t\tassertBig(17, Integer.MAX_VALUE);\n\t}\n\n\tprivate void assertBig(int... values) {\n\t\tfor (int v : values) {\n\t\t\tassertBig(v);\n\t\t}\n\t}\n\n\tprivate void assertBig(int value) {\n\t\tassertTrue(\"big number: \" + value, value \u003c Short.MAX_VALUE);\n\t}\n}\n\n\njunit.framework.AssertionFailedError: big number: 17\n\tat junit.framework.Assert.fail(Assert.java:47)\n\tat junit.framework.Assert.assertTrue(Assert.java:20)\n\tat junit.samples.Failing.assertBig(Failing.java:17)\n\tat junit.samples.Failing.assertBig(Failing.java:12)\n\tat junit.samples.Failing.testFail(Failing.java:7)\n",
    "Yes please!",
    "Fixed in HEAD.\n\n(In reply to comment #6)\nI just select the first occurrence of the test method in the stack trace, i.e.\njunit.samples.Failing.testFail(Failing.java:7) in the example. Selecting the concrete assertion failure inside another method would be confusing.\n"
  ],
  "commentCreationDates": [
    "2004-06-28T13:09:43+02:00",
    "2004-06-28T18:53:00+02:00",
    "2004-06-29T08:55:53+02:00",
    "2004-06-30T12:32:34+02:00",
    "2006-05-24T11:48:30+02:00",
    "2006-06-23T20:02:22+02:00",
    "2006-06-26T12:10:16+02:00",
    "2007-10-05T09:13:03+02:00",
    "2007-10-09T16:14:11+02:00"
  ],
  "traces": [
    {
      "exceptionType": "junit.framework.AssertionFailedError",
      "message": "Logs should have shrunk when becoming \u003e maxTotalLogSize bytes",
      "elements": [
        {
          "method": "junit.framework.Assert.fail",
          "source": "Ljava/lang/String;"
        }
      ],
      "number": 0,
      "commentIndex": 2,
      "bugId": "68738",
      "date": "2004-06-29T08:55:53+02:00",
      "product": "JDT",
      "component": "UI",
      "severity": "enhancement"
    },
    {
      "exceptionType": "junit.framework.AssertionFailedError",
      "message": "big number: 17",
      "elements": [
        {
          "method": "junit.framework.Assert.fail",
          "source": "Assert.java:47"
        },
        {
          "method": "junit.framework.Assert.assertTrue",
          "source": "Assert.java:20"
        },
        {
          "method": "junit.samples.Failing.assertBig",
          "source": "Failing.java:17"
        },
        {
          "method": "junit.samples.Failing.assertBig",
          "source": "Failing.java:12"
        },
        {
          "method": "junit.samples.Failing.testFail",
          "source": "Failing.java:7"
        }
      ],
      "number": 1,
      "commentIndex": 6,
      "bugId": "68738",
      "date": "2006-06-26T12:10:16+02:00",
      "product": "JDT",
      "component": "UI",
      "severity": "enhancement"
    }
  ],
  "groupId": "68738",
  "bugId": "68738",
  "date": "2004-06-28T13:09:43+02:00",
  "product": "JDT",
  "component": "UI",
  "severity": "enhancement"
}