{
  "comments": [
    "a declared enum type \n\npublic enum RuleType{ AVAILABLE, MANDATORY }\n\nhas the generated method RuleType.valueOf(String)\n\nthis call chokes with an ArrayIndexOutOfBoundsException when called with valid\nvalues:\n\nRuleType.valueOf(RuleType.AVAILABLE.name())",
    "The exception happens at runtime.\n\npublic class X {\n\tpublic enum RuleType{ AVAILABLE, MANDATORY }\n\tpublic static void main(String[] args) {\n\t\tSystem.out.println(RuleType.valueOf(RuleType.AVAILABLE.name()));\n\t}\n}\n\nException in thread \"main\" java.lang.ArrayIndexOutOfBoundsException: 2\n\tat X$RuleType.valueOf(X.java:1)\n\tat X.main(X.java:5)\n",
    "Created an attachment (id\u003d15457)\nApply on HEAD\n\nWith this patch the code works.\nThree errors found:\nThe code is doing a reverse loop on the values array, but it doesn\u0027t take:\n- length - 1 for the first index\n- doesn\u0027t get the name() of the current entry\n- stop one two earlier (gt instead of ge)",
    "I get:\n\nC:\\tests_sources\u003ejava X\nAVAILABLE",
    "We could also use the method:\npublic static \u003cT extends Enum\u003cT\u003e\u003e T valueOf(Class\u003cT\u003e enumType,\n                                            String name)\n\ndefined on java.lang.Enum.",
    "Pls also update the comment in front:\n//\tstatic X valueOf(String name) {\n//\t\tX[] values;\n//\t\tfor (int i \u003d (values \u003d $VALUES).length; --i \u003e\u003d 0;) {\n//\t\t\tX value;\n//\t\t\tif (name.equals(value \u003d values[i].name())) return value;\n//\t\t}\n//\t\tthrow new IllegalArgumentException(name);\n//\t}\t\t",
    "Fixed and released in HEAD.\nRegression test added in EnumTest.",
    "Verified for 3.1M3 with build I20041102"
  ],
  "commentCreationDates": [
    "2004-10-28T18:28:52+02:00",
    "2004-10-28T18:39:30+02:00",
    "2004-10-28T22:40:46+02:00",
    "2004-10-28T22:41:27+02:00",
    "2004-10-28T22:56:48+02:00",
    "2004-10-28T23:29:03+02:00",
    "2004-10-28T23:51:33+02:00",
    "2004-11-04T09:25:25+01:00"
  ],
  "traces": [
    {
      "exceptionType": "java.lang.ArrayIndexOutOfBoundsException",
      "message": "2",
      "elements": [
        {
          "method": "X$RuleType.valueOf",
          "source": "X.java:1"
        },
        {
          "method": "X.main",
          "source": "X.java:5"
        }
      ],
      "number": 0,
      "commentIndex": 1,
      "bugId": "77212",
      "date": "2004-10-28T18:39:30+02:00",
      "product": "JDT",
      "component": "Core",
      "severity": "normal"
    }
  ],
  "groupId": "77212",
  "bugId": "77212",
  "date": "2004-10-28T18:28:52+02:00",
  "product": "JDT",
  "component": "Core",
  "severity": "normal"
}