{
  "comments": [
    "Automated test suite failure:\n\nProgram did not suspend, launch terminated. \n\njunit.framework.AssertionFailedError: Program did not suspend, launch \nterminated.\nat org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndWait\n(AbstractDebugTest.java:235)\nat org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndWait\n(AbstractDebugTest.java:195)\nat org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndSuspend\n(AbstractDebugTest.java:264)\nat org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndSuspend\n(AbstractDebugTest.java:250)\nat \norg.eclipse.jdt.debug.tests.core.MiscBreakpointsTests.testSuspendOnUncaughtExce\nptions(MiscBreakpointsTests.java:46)\nat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\nat sun.reflect.NativeMethodAccessorImpl.invoke\n(NativeMethodAccessorImpl.java:39)\nat sun.reflect.DelegatingMethodAccessorImpl.invoke\n(DelegatingMethodAccessorImpl.java:25)\nat org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:53)\nat java.lang.Thread.run(Thread.java:534)\n\nI believe the test is failing due to the change in debug event dispatch. \nEvents are not fired asynchronously, in a seperate thread. So, the target is \ncreated and continues executing, while a breakpoint is installed in a seperate \njob. This allows the target to complete executing before it has a chance to \ninstall the exception breakpoint.",
    "Fixed in JDIDebugTarget.\n\n* Since event listeners may want to perform synchronous \"stuff\" on CREATION of \na debug target, the JDIDebugTarget now waits for the CREATION event to \npropogate before starting event dispatch (resuming the VM). The target listens \nfor the event to come back to itself before starting event dispatch.\n* Also modified AbstractDebugTest/ProjectCreationDecorator/MiscBreakpointTests \nto properly set/restore suspend preferences. ",
    "Please verify, Luc.",
    "Verified."
  ],
  "commentCreationDates": [
    "2005-01-05T15:31:59+01:00",
    "2005-01-05T17:30:34+01:00",
    "2005-01-05T17:30:54+01:00",
    "2005-01-05T18:20:48+01:00"
  ],
  "traces": [
    {
      "exceptionType": "junit.framework.AssertionFailedError",
      "message": "Program did not suspend, launch  terminated.",
      "elements": [
        {
          "method": "org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndWait",
          "source": "AbstractDebugTest.java:235"
        },
        {
          "method": "org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndWait",
          "source": "AbstractDebugTest.java:195"
        },
        {
          "method": "org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndSuspend",
          "source": "AbstractDebugTest.java:264"
        },
        {
          "method": "org.eclipse.jdt.debug.tests.AbstractDebugTest.launchAndSuspend",
          "source": "AbstractDebugTest.java:250"
        },
        {
          "method": "org.eclipse.jdt.debug.tests.core.MiscBreakpointsTests.testSuspendOnUncaughtExceptions",
          "source": "MiscBreakpointsTests.java:46"
        },
        {
          "method": "sun.reflect.NativeMethodAccessorImpl.invoke0",
          "source": "Native Method"
        },
        {
          "method": "sun.reflect.NativeMethodAccessorImpl.invoke",
          "source": "NativeMethodAccessorImpl.java:39"
        },
        {
          "method": "sun.reflect.DelegatingMethodAccessorImpl.invoke",
          "source": "DelegatingMethodAccessorImpl.java:25"
        },
        {
          "method": "org.eclipse.jdt.debug.tests.DebugSuite$1.run",
          "source": "DebugSuite.java:53"
        },
        {
          "method": "java.lang.Thread.run",
          "source": "Thread.java:534"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "82244",
      "date": "2005-01-05T15:31:59+01:00",
      "product": "JDT",
      "component": "Debug",
      "severity": "normal"
    }
  ],
  "groupId": "82244",
  "bugId": "82244",
  "date": "2005-01-05T15:31:59+01:00",
  "product": "JDT",
  "component": "Debug",
  "severity": "normal"
}